version: '3.9'
services:
  bdd:
    image: mongo:5.0.4
    volumes:
      - ${MONGO_BACKUP:-./mongo_data}:/data/db
      # - ./bdd:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-foraigner_cp4FDt}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-aovxKafANoIU3qPl}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-foraigner}
    ports:
      - 27017:27017
  redis:
    container_name: redis-dev
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  

