version: '3.9'
services:
  front:
    restart: unless-stopped
    build:
      context: ./front
      args:
        REACT_APP_API_BASE: ${API_BASE}
    ports:
      - '8089:80'
      # Api on port 8090 
