name: Pipeline
on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add .env
        run: echo -e "${{ secrets.ENV }}\nCOMMIT_HASH='${{ github.sha }}'" > .env
      - name: Build FRONT Images
        run: docker-compose build front
  unit-test:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    needs: build
  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
    needs: build
  e2e-test:
    uses: ./.github/workflows/end-to-end-tests.yml
    secrets: inherit
    needs: build
  deploy:
    if: github.repository == 'Oriun/the-foraigner'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ github.repository }} 
            git pull 
            echo -e "${{ secrets.ENV }}\nCOMMIT_HASH='${{ github.sha }}'" > .env 
            docker-compose build
            docker-compose up -d --force-recreate
