export const data: Record<string, string[][]> = {
  0: [
    ["Sonia", "is", "(be) the most beautiful girl in my campus."],
    ["Look at the door! Tom", "open", "(open) it now."],
    ["I", "ran", "(run) as soon as they told me so."],
    ["Koffi and Mary", "won", "(win) National cup of Tennis two months ago."],
    [
      "We never",
      "swim",
      "(swim) in the Pacific Ocean. I",
      "would",
      "(will) like to go there.",
    ],
    [
      "Joe didn't go to Germany with USA football team. He wishes he",
      "were",
      "(be) their goalkeeper.",
    ],
    ["When I", "played", "(played) tennis last morning,I won every match"],
    ["My sister often", "cooked", "(cook) delicious cakes"],
    ["I", "became", "(become) a pilot if I was very good at Mathematics."],
    [
      "Anna",
      "show",
      "(show) me the right way to come back from school on Mondays.",
    ],
  ],
  1: [
    ["She", "bought", "(buy) a new dress for the party."],
    ["The sun", "rises", "(rise) in the east."],
    ["They", "went", "(go) to the museum last weekend."],
    ["Martin", "plays", "(play) the guitar in a band."],
    ["Cats", "sleep", "(sleep) most of the day."],
    ["We", "visited", "(visit) the Eiffel Tower during our trip to Paris."],
    ["Lucy", "reads", "(read) a book before going to bed every night."],
    ["He", "worked", "(work) as a waiter before becoming an actor."],
    ["The children", "swam", "(swim) in the pool all afternoon."],
    ["Samantha", "wrote", "(write) a letter to her grandmother."],
  ],
  2: [
    ["Our dog", "loves", "(love) chasing squirrels in the park."],
    ["She", "lived", "(live) in Italy for two years."],
    ["The baby", "cried", "(cry) all night long."],
    ["I", "studied", "(study) French in high school."],
    ["They", "enjoy", "(enjoy) going to the movies on Saturdays."],
    ["Alice", "drinks", "(drink) coffee every morning."],
    ["Max", "forgot", "(forget) his umbrella at home."],
    ["She", "washed", "(wash) the dishes after dinner."],
    ["He", "passed", "(pass) the exam with flying colors."],
    ["They", "traveled", "(travel) to Japan last year."],
  ],
  3: [
    ["The cat", "climbed", "(climb) the tree to catch the bird."],
    ["I", "watched", "(watch) my favorite show last night."],
    ["John", "gave", "(give) Sara a gift for her birthday."],
    ["She", "sang", "(sing) in the choir at church."],
    ["They", "planted", "(plant) flowers in the garden."],
    ["Mike", "lost", "(loose) his wallet on the bus."],
    ["I", "found", "(found) a twenty-dollar bill on the sidewalk."],
    ["The teacher", "explained", "(explain) the lesson to the students."],
    ["He", "tried", "(try) to fix the broken window."],
    [
      "They",
      "celebrated",
      "(celebrate) their anniversary at a fancy restaurant.",
    ],
  ],
  4: [
    ["I", "met", "(meet) my best friend in college."],
    ["She", "painted", "(paint) a beautiful picture of a sunset."],
    ["The dog", "barked", "(bark) loudly at the mail carrier."],
    ["The students", "finished", "(finish) the project on time."],
    ["He", "listened", "(listen) to the music on his headphones."],
    ["We", "ate", "(eat) pizza for dinner last night."],
    ["She", "practiced", "(practice) yoga every morning."],
    ["The rain", "stopped", "(stop) after a few hours."],
    ["He", "built", "(build) a treehouse for his kids."],
    ["They", "hiked", "(hike) to the top of the mountain."],
  ],
  5: [
    ["Sara", "wears", "(wear) glasses to read."],
    ["He", "cooked", "(cook) spaghetti for dinner."],
    ["The birds", "flew", "(fly) south for the winter."],
    ["I", "dreamed", "(dream) about traveling the world."],
    ["They", "laughed", "(laugh) at the funny movie."],
    ["He", "fixed", "(fix) the leaky faucet in the kitchen."],
    ["The flowers", "bloomed", "(bloom) in the springtime."],
    ["I", "joined", "(join) a sports club to get fit."],
    ["They", "danced", "(dance) all night at the wedding."],
    ["She", "baked", "(baked) cookies for the school bake sale."],
  ],
  6: [
    ["The train", "arrived", "ten minutes late."],
    ["She", "cut", "her finger while chopping vegetables."],
    ["They", "rented", "a car for their road trip."],
    ["I", "mailed", "the package to my friend."],
    ["The children", "played", "hide-and-seek in the park."],
    ["He", "photographed", "the beautiful scenery on his vacation."],
    ["We", "walked", "along the beach at sunset."],
    ["She", "brushed", "her hair before going to bed."],
    ["He", "taught", "English in a foreign country."],
    ["They", "shared", "a pizza for lunch."],
  ],
  7: [
    ["The movie", "started", "at 8 pm."],
    ["She", "knitted", "a scarf for her mother."],
    ["I", "wrote", "a poem for the poetry contest."],
    ["They", "rowed", "a boat across the lake."],
    ["He", "jogged", "three miles every morning."],
    ["The cat", "purred", "contentedly on the sofa."],
    ["I", "picked", "fresh strawberries from the garden."],
    ["She", "sewed", "a dress for the costume party."],
    ["He", "raked", "the leaves in the front yard."],
    ["They", "skated", "on the frozen pond."],
  ],
  8: [
    ["The wind", "blew", "the papers off the table."],
    ["She", "waved", "goodbye to her friends."],
    ["The dog", "dug", "a hole in the backyard."],
    ["I", "borrowed", "a book from the library."],
    ["They", "fished", "at the lake all day."],
    ["He", "invented", "a new gadget for the kitchen."],
    ["We", "painted", "the living room a light blue color."],
    ["She", "watered", "the plants in the garden."],
    ["He", "stacked", "the firewood for the winter."],
    ["They", "rode", "bicycles through the countryside."],
  ],
  9: [
    ["The sun", "set", "behind the mountains."],
    ["She", "folded", "the laundry neatly."],
    ["I", "tasted", "the soup to check the seasoning."],
    ["They", "climbed", "the stairs to the top floor."],
    ["He", "whistled", "while he worked."],
    ["The snow", "melted", "quickly in the sun."],
    ["I", "carved", "a pumpkin for Halloween."],
    ["She", "ironed", "her clothes for the interview."],
    ["He", "pruned", "the bushes in the front yard."],
    ["They", "sledded", "down the snowy hill."],
  ],
  10: [
    ["The moon", "shone", "brightly in the night sky."],
    ["She", "tidied", "her room before her guests arrived."],
    ["I", "sipped", "my coffee slowly, enjoying the flavor."],
    ["They", "jumped", "into the pool to cool off."],
    ["He", "strummed", "his guitar, composing a new song."],
    ["The leaves", "rustled", "in the gentle breeze."],
    ["I", "arranged", "the flowers in a vase."],
    ["She", "peeled", "the apples for the pie."],
    ["He", "shoveled", "the snow from the driveway."],
    ["They", "strolled", "through the park, enjoying the scenery."],
  ],
};
