name: CI
# on:
#   push: 
#     branches:
#       - master
#   workflow_dispatch:

jobs:
  build_front:
    runs-on: ubuntu-latest
    if: github.repository == 'Oriun/the-foraigner'
    steps:
      - uses: actions/checkout@v3

      - name: Add .env
        run: echo -e "${{ secrets.ENV }}\nREACT_APP_COMMIT_HASH='${{ github.sha }}'" > .env

      - name: Build Image
        run: docker build -t front-${{ github.sha }} front

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Image with sha
        run: docker image tag front-${{ github.sha }} ${{ secrets.DOCKER_USER }}/foraigner:front-${{ github.sha }}

      - name: Push Image with sha
        run: docker image push ${{ secrets.DOCKER_USER }}/foraigner:front-${{ github.sha }}

      - name: Tag Image as lts
        run: docker image tag front-${{ github.sha }} ${{ secrets.DOCKER_USER }}/foraigner:front-lts

      - name: Push Image as lts
        run: docker image push ${{ secrets.DOCKER_USER }}/foraigner:front-lts

  test_back:
    runs-on: ubuntu-latest
    if: github.repository == 'Oriun/the-foraigner'
    steps:
      - uses: actions/checkout@v3

      ########################## TESTS
      - name: example
        run: echo 'ok'

  build_back:
    runs-on: ubuntu-latest
    if: github.repository == 'Oriun/the-foraigner'
    steps:
      - uses: actions/checkout@v3

      - name: Add .env
        run: echo -e "${{ secrets.ENV }}\nREACT_APP_COMMIT_HASH='${{ github.sha }}'" > .env

      - name: Build Image
        run: docker build -t back-${{ github.sha }} api
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Image with sha
        run: docker image tag back-${{ github.sha }} ${{ secrets.DOCKER_USER }}/foraigner:back-${{ github.sha }}

      - name: Push Image with sha
        run: docker image push ${{ secrets.DOCKER_USER }}/foraigner:back-${{ github.sha }}

      - name: Tag Image as lts
        run: docker image tag back-${{ github.sha }} ${{ secrets.DOCKER_USER }}/foraigner:back-lts

      - name: Push Image as lts
        run: docker image push ${{ secrets.DOCKER_USER }}/foraigner:back-lts

  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'Oriun/the-foraigner'
    steps:
      - name: Pull Images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            mkdir -p /home/deployer/${{ github.repository }}/${{ github.refname }} && cd "$_"
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USER }}/foraigner:front-lts
            docker pull ${{ secrets.DOCKER_USER }}/foraigner:back-lts

      - name: Update docker compose
        uses: garygrossgarten/github-action-scp@release
        with:
          local: docker-compose.yml
          remote: /home/deployer/${{ github.repository }}/${{ github.refname }}/docker-compose.yml
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}

      - name: Start Docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/deployer/${{ github.repository }}/${{ github.refname }}
            echo -e "${{ secrets.ENV }}\nCOMMIT_HASH='${{ github.sha }}'" > .env
            docker compose up -d --force-recreate