name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.repository == 'Oriun/the-foraigner'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Replacing origin
        run: |
          git remote remove origin
          git remote add origin git@github.com:EpitechMscProPromo2023/T-ESP-800-19605-The-Foraigner-2.git
          git remote add old git@github.com:Oriun/the-foraigner.git
          
      - name: Add ssh key
        run: |
          echo '${{ secrets.SSH_KEY }}' > ../key
          chmod 400 ../key
        
      - name: print ssh key
        run: cat ../key
        
      # Runs a single command using the runners shell
      - name: Fetch and push
        run: |
          ssh-agent bash -c 'ssh-add ../key; git fetch --unshallow old; git push -f --set-upstream origin master'
