name: Pipeline
on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    if: github.repository == 'Oriun/the-foraigner'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add .env
        run: echo -e "${{ secrets.ENV }}\nCOMMIT_HASH='${{ github.sha }}'" > .env
      - name: Build FRONT Images
        run: docker-compose run front npm run unit-test
