name: Pipeline
on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    if: github.repository == 'Oriun/the-foraigner'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add .env
        run: echo -e "${{ secrets.ENV }}\nCOMMIT_HASH='${{ github.sha }}'" > .env
      - name: Build FRONT Images
        run: docker-compose build front
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add .env
        run: echo -e "${{ secrets.ENV }}\nCOMMIT_HASH='${{ github.sha }}'" > .env
      - name: Run Unit tests
        run: docker-compose run --rm api npm run unit-test
      - name: Run Unit tests
        run: docker-compose run --rm api npm run integration-test
      - name: Run End-To-End tests
        run: docker-compose run --rm api npm run e2e-test
  deploy:
    if: github.repository == 'Oriun/the-foraigner'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_ADDRESS }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ github.repository }} 
            git pull 
            echo -e "${{ secrets.ENV }}\nCOMMIT_HASH='${{ github.sha }}'" > .env 
            docker-compose build
            docker-compose up -d --force-recreate
